model:
  resume: False
  amp: True
  base_learning_rate: 1.0e-4
  params:
    embed_dim: 4
    predictioner: True
    lossconfig:
      params:
        disc_start: 1000

    ddconfig:
      double_z: False
      channels: 384
      resolution: 256
      timesteps: 12
      skip: 1
      in_channels: 1
      out_ch: 1
      num_res_blocks: 2
      attn_resolutions: []
      splits: 1
